// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQWYyrVwvrBBnXLs9rV4HSxwtqKoed3pk',
    appId: '1:865831873810:web:a8b23c7b3094b1e97e17cb',
    messagingSenderId: '865831873810',
    projectId: 'todo-app-ecfc5',
    authDomain: 'todo-app-ecfc5.firebaseapp.com',
    storageBucket: 'todo-app-ecfc5.appspot.com',
    measurementId: 'G-Y9YKP5MT41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXIiwDzoyzALUtCIYsxfx3iPgR8IivunY',
    appId: '1:865831873810:android:fa1bd59536fa4f4b7e17cb',
    messagingSenderId: '865831873810',
    projectId: 'todo-app-ecfc5',
    storageBucket: 'todo-app-ecfc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcTWiN-KdODad-mO56g0oxNXSw4p-kH8c',
    appId: '1:865831873810:ios:0af583702d183cb97e17cb',
    messagingSenderId: '865831873810',
    projectId: 'todo-app-ecfc5',
    storageBucket: 'todo-app-ecfc5.appspot.com',
    iosClientId: '865831873810-6avrpgja7kj2laqd4ga88holoitov5h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcTWiN-KdODad-mO56g0oxNXSw4p-kH8c',
    appId: '1:865831873810:ios:0af583702d183cb97e17cb',
    messagingSenderId: '865831873810',
    projectId: 'todo-app-ecfc5',
    storageBucket: 'todo-app-ecfc5.appspot.com',
    iosClientId: '865831873810-6avrpgja7kj2laqd4ga88holoitov5h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
